---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      serviceAccountName: goormprj
      containers:
      - image: sulmoon/auth-svc:176
        name: auth-svc
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secret/goormprj"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "goormprj"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      serviceAccountName: goormprj
      containers:
      - image: sulmoon/survey-svc:176
        name: survey-svc
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secret/goormprj"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "goormprj"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      serviceAccountName: goormprj
      containers:
      - image: sulmoon/user-svc:176
        name: user-svc
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secret/goormprj"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "goormprj"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon-gate
  template:
    metadata:
      labels:
        app: sulmoon-gate
    spec:
      containers:
      - image: sulmoon/api-gateway-svc:176
        name: api-gateway
        ports:
        - containerPort: 10000
      nodeSelector:
        node: svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/discovery-svc:176
        name: discovery-svc
        ports:
        - containerPort: 8761
      nodeSelector:
        node: svc
