---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sulmoon
  template:
    metadata:
      labels:
        run: sulmoon
    spec:
      containers:
      - image: sulmoon/auth-svc:160
        name: auth-svc
        ports:
        - containerPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sulmoon
  template:
    metadata:
      labels:
        run: sulmoon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sulmoon
  template:
    metadata:
      labels:
        run: sulmoon
    spec:
      containers:
      - image: sulmoon/survey-svc:160
        name: survey-svc
        ports:
        - containerPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sulmoon
  template:
    metadata:
      labels:
        run: sulmoon
    spec:
      containers:
      - image: sulmoon/user-svc:160
        name: user-svc
        ports:
        - containerPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sulmoon
  template:
    metadata:
      labels:
        run: sulmoon
    spec:
      containers:
      - image: sulmoon/api-gateway-svc:160
        name: api-gateway
        ports:
        - containerPort: 80
      nodeSelector:
        node: svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sulmoon
  template:
    metadata:
      labels:
        run: sulmoon
    spec:
      containers:
      - image: sulmoon/discovery-svc:160
        name: discovery-svc
        ports:
        - containerPort: 9091
      nodeSelector:
        node: svc
