---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/auth-svc:179
        name: auth-svc
      serviceAccountName: sulmoon-deployment-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/survey-svc:179
        name: survey-svc
      serviceAccountName: sulmoon-deployment-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/user-svc:179
        name: user-svc
      serviceAccountName: sulmoon-deployment-sa
