---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sulmoon-auth
spec:
  serviceName: sulmoon-auth-svc
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon-auth
  template:
    metadata:
      labels:
        app: sulmoon-auth
    spec:
      containers:
      - image: sulmoon/auth-svc:192
        name: auth-svc
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secret/"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sulmoon-survey
spec:
  serviceName: sulmoon-survey-svc
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon-survey
  template:
    metadata:
      labels:
        app: sulmoon-survey
    spec:
      containers:
      - image: sulmoon/survey-svc:192
        name: survey-svc
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - name: secrets-store02-inline
          mountPath: "/secret/"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store02-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sulmoon-user
spec:
  serviceName: sulmoon-user-svc
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon-user
  template:
    metadata:
      labels:
        app: sulmoon-user
    spec:
      containers:
      - image: sulmoon/user-svc:192
        name: user-svc
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - name: secrets-store03-inline
          mountPath: "/secret/"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store03-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
