---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sulmoon-api-gateway
spec:
  serviceName: gateway
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon-gate
  template:
    metadata:
      labels:
        app: sulmoon-gate
    spec:
      containers:
      - image: sulmoon/api-gateway-svc:192
        name: api-gateway
        ports:
        - containerPort: 10000
      nodeSelector:
        topology.kubernetes.io/zone: ap-northeast-2a
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sulmoon-discovery
spec:
  serviceName: discovery
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon-dis
  template:
    metadata:
      labels:
        app: sulmoon-dis
    spec:
      containers:
      - image: sulmoon/discovery-svc:192
        name: discovery-svc
        ports:
        - containerPort: 8761
      nodeSelector:
        topology.kubernetes.io/zone: ap-northeast-2a
