---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      hostname: sulmoon-auth-0.default.svc.cluster.local
      containers:
      - image: sulmoon/auth-svc:192
        name: auth-svc
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secret/"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/survey-svc:192
        name: survey-svc
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - name: secrets-store02-inline
          mountPath: "/secret/"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store02-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/user-svc:192
        name: user-svc
        envFrom:
        - configMapRef:
            name: appconfig
        volumeMounts:
        - name: secrets-store03-inline
          mountPath: "/secret/"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store03-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
