---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/auth-svc:176
        name: auth-svc
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-survey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/survey-svc:176
        name: survey-svc
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sulmoon-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sulmoon
  template:
    metadata:
      labels:
        app: sulmoon
    spec:
      containers:
      - image: sulmoon/user-svc:176
        name: user-svc
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      serviceAccountName: sulmoon-deployment-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "sulmoon-secret-provider"
