apiVersion: v1
kind: Service
metadata:
  name: sulmoon-svc
  labels: 
    app: sulmoon-gate
    run: sulmoon
spec:
  clusterIP: 10.100.75.225
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  type: LoadBalancer
  selector:
    app: sulmoon-gate
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-service
  labels: 
    app: sulmoon
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sulmoon
