apiVersion: v1
kind: Service
metadata:
  name: sulmoon-svc
  labels: 
    app: sulmoon-gate
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  type: LoadBalancer
  selector:
    app: sulmoon-gate
