apiVersion: v1
kind: Service
metadata:
  name: sulmoon-gate-svc
  labels: 
    app: sulmoon-gate
spec:
  clusterIP: 10.100.75.225
  ports:
  - port: 80
    protocol: TCP
    targetPort: 10000
  type: LoadBalancer
  selector:
    app: sulmoon-gate
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-dis-svc
  labels: 
    app: sulmoon-dis
spec:
  clusterIP: 10.100.75.235
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8761
  type: LoadBalancer
  selector:
    app: sulmoon-dis
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-user-svc
  labels:
    app: sulmoon-user
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sulmoon-user
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-auth-svc
  labels:
    app: sulmoon-auth
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sulmoon-auth
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-survey-svc
  labels:
    app: sulmoon-survey
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sulmoon-survey
