apiVersion: v1
kind: Service
metadata:
  name: sulmoon-gate-svc
  labels: 
    app: sulmoon-gate
spec:
  clusterIP: 10.100.75.225
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  type: LoadBalancer
  selector:
    app: sulmoon-gate
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-dis-svc
  labels: 
    app: sulmoon-dis
spec:
  clusterIP: 10.100.75.235
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  type: LoadBalancer
  selector:
    app: sulmoon-dis
---
apiVersion: v1
kind: Service
metadata:
  name: sulmoon-svc
  labels:
    app: sulmoon
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sulmoon
